name: Create Infrastructure

on:
  workflow_dispatch:
  push:

concurrency: creating

jobs:
  Setup-Infra:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@master
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - uses: azure/arm-deploy@v1
      id: deploy
      with:
        scope: subscription
        deploymentMode: Incremental
        deploymentName: "Main-Deploy"
        template: ./bicep/main.bicep
        parameters: 'storagePrefix=mystore resourceGroupName=Flux-Podidentity-Demo location=north-europe'
        failOnStdErr: true