name: Create Infrastructure

on:
  workflow_dispatch:
  push:

env:
  RESOURCE_GROUP: Flux-Podidentity-Demo

concurrency: creating

jobs:
  Setup-Infra:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@master
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - uses: azure/arm-deploy@v1
      id: deploy
      with:
        resourceGroupName: ${{ env.RESOURCE_GROUP }}
        deploymentMode: Incremental
        deploymentName: "Main-Deploy"
        template: ./bicep/main.bicep
        parameters: 'storagePrefix=mystore storageSKU=Standard_LRS'
        failOnStdErr: true